name: Continuous Deployment

on:
  push:
    tags: [v*]

jobs:
  publish:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: asdf-vm/actions/install@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Log into NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Set up NPMrc
        run: echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}' >> ~/.npmrc

      - name: Publish to NPM
        run: npm publish
