name: Continuous Deployment

on:
  push:
    tags: [v*]

jobs:
  publish:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: asdf-vm/actions/install@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
